### ISSUE TITLE
Course import failing when plugin already present

### ISSUE THREAD

**Issue by joe-allen-89** [adapt-security/adapt-authoring-adaptframework#37]
### What happened?

When importing a course if any of the plugins being imported are already in the tool the import fails with the below error visible in the tool:

![image](https://github.com/adapt-security/adapt-authoring-adaptframework/assets/85872286/ad586e60-f8be-4e7a-be88-483abdd0231c)

And the below errors in the console: 

2024-01-09T12:31:51.080Z error adaptframework PLUGIN_IMPORT_FAILED C:\Working-AuthoringTool\240104\adapt-authoring\APP_DATA\temp\file-uploads\f3fa00c24854b0bd1cd945313_unzip\src\menu\adapt-contrib-boxMenu AdaptError: CONTENTPLUGIN_INSTALL_FAILED
    at Object.get [as CONTENTPLUGIN_INSTALL_FAILED] (file:///C:/Working-AuthoringTool/240104/adapt-authoring/node_modules/adapt-authoring-errors/lib/ErrorsModule.js:50:20)
    at ContentPluginModule.installPlugins (file:///C:/Working-AuthoringTool/240104/adapt-authoring/node_modules/adapt-authoring-contentplugin/lib/ContentPluginModule.js:246:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Working-AuthoringTool/240104/adapt-authoring/node_modules/adapt-authoring-adaptframework/lib/AdaptFrameworkImport.js:463:34
    at async Promise.all (index 0)
    at async AdaptFrameworkImport.importCoursePlugins (file:///C:/Working-AuthoringTool/240104/adapt-authoring/node_modules/adapt-authoring-adaptframework/lib/AdaptFrameworkImport.js:453:7)
    at async AdaptFrameworkImport.import (file:///C:/Working-AuthoringTool/240104/adapt-authoring/node_modules/adapt-authoring-adaptframework/lib/AdaptFrameworkImport.js:221:9)
    at async importHandler (file:///C:/Working-AuthoringTool/240104/adapt-authoring/node_modules/adapt-authoring-adaptframework/lib/AdaptFrameworkUtils.js:219:24) {
  code: 'CONTENTPLUGIN_INSTALL_FAILED',
  statusCode: 500,
  meta: {
    description: 'Installation of plugins failed',
    data: { errors: 'List of errors' }
  },
  data: { errors: [ [AdaptError] ] }
}

### Steps to reproduce

Import any course with a plugin already loaded into the tool

### Authoring tool version

latest master

### Framework version

5.33.13

### What browsers are you seeing the problem on?

Firefox

**Comment by taylortom** [comment]
Can't replicate this locally, have tested with plugins with both the same _and_ out-of-sync versions. 

Do you have any tips on how to replicate?

**Comment by chris-steele** [comment]
FYI I've been looking into this and possibly related issues

**Comment by taylortom** [comment]
Can this be closed?

**Comment by chris-steele** [comment]
looking at the OP error and trace, this is exactly what I had prior to the fix in https://github.com/adapt-security/adapt-authoring-adaptframework/pull/42

Propose this is closed.

**Comment by taylortom** [comment]
Cool, yep that's what I thought
